---
- name: Generate prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
  become: true
  notify:
    - Restart prometheus

- name: Generate prometheus docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_config_dir }}/docker-compose.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
  become: true
  notify:
    - Restart prometheus

- name: Generate prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/{{ prometheus_service_name }}.service
    mode: '0644'
  become: true
  notify:
    - Restart prometheus

- name: Enable and start prometheus service
  ansible.builtin.systemd:
    name: "{{ prometheus_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
  become: true
